airtkts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'airtkts.views.home', name='home'),

    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^invite/expired/(?P<event_id>[0-9]+)/$', 'airtkts.views.invite_expired', name='invite_expired'),
    url(r'^invite/invalid/$', 'airtkts.views.invite_invalid', name='invite_invalid'),
    url(r'^invite/(?P<invite_key>\w+)/$', 'airtkts.views.invite_serve', name='invite_serve'),
    url(r'^event/(?P<event_id>[0-9]+)/(?P<event_slug>\w+)', 'airtkts.views.ticket_office', name='ticket_office'),
    url(r'^confirm/(?P<order_id>[0-9]+)/$', 'airtkts.views.order_confirmation', name='order_confirmation'),

    # Account Home
    url(r'^accounts/$', 'airtkts.views.accounts_home', name='accounts_home'),

    # User Pages
    url(r'^accounts/users/$', 'airtkts.views.users_home', name='users_home'),
    url(r'^accounts/users/new$', 'airtkts.views.users_new', name='users_new'),
    url(r'^accounts/users/(?P<user_id>[\-0-9]+)/$', 'airtkts.views.users_edit', name='users_edit'),
    url(r'^accounts/users/(?P<user_id>[\-0-9]+)/password/$', 'airtkts.views.users_edit_password', name='users_edit_password'),
    url(r'^accounts/users/me/$', 'airtkts.views.users_edit', {'self_edit': True}, name='account_edit'),

    # Account Event Pages
    url(r'^accounts/event/$', 'airtkts.views.event_home', name='event_home'),
    url(r'^accounts/event/new/$', 'airtkts.views.event_form', name='event_new'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/$', 'airtkts.views.event_dashboard', name='event_dashboard'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/edit/$', 'airtkts.views.event_form', name='event_edit'),

    url(r'^accounts/event/(?P<event_id>[0-9]+)/hosts/$', 'airtkts.views.hosts_home', name='hosts_home'),
    url(r'^accounts/hosts/search/$', 'airtkts.views.host_search', name='host_search'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/hosts/new/$', 'airtkts.views.hosts_new', name='hosts_new'),

    # Ticket Sales
    url(r'^accounts/event/(?P<event_id>[0-9]+)/tickets/$', 'airtkts.views.ticketsales_home', name='ticketsales_home'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/tickets/(?P<ticket_id>[0-9]+)/$', 'airtkts.views.ticketsales_form',
        name='ticketsales_edit'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/tickets/new/$', 'airtkts.views.ticketsales_form', name='ticketsales_new'),

    # Invites
    url(r'^accounts/event/(?P<event_id>[0-9]+)/invites/$', 'airtkts.views.invites_home', name='invites_home'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/invites/(?P<invite_id>[0-9]+)/$', 'airtkts.views.invites_form',
        name='invites_edit'),
    url(r'^accounts/event/(?P<event_id>[0-9]+)/invites/new/$', 'airtkts.views.invites_form', name='invites_new'),

    # Check In
    url(r'^accounts/event/(?P<event_id>[0-9]+)/checkin/$', 'airtkts.views.check_in_home', name='check_in'),

    url(r'^admin/', include(admin.site.urls)),

    # Account Pages
    url(r'^accounts/login/$',
       auth_views.login,
       {'template_name': 'auth/login.html'},
       name='auth_login'),
    url(r'^accounts/logout/$',
       auth_views.logout,
       {'template_name': 'auth/logout.html'},
       name='auth_logout'),
    url(r'^accounts/password/change/$',
       auth_views.password_change,
        {'template_name': 'auth/password_change_form.html'},
       name='auth_password_change'),
    url(r'^accounts/password/change/done/$',
       auth_views.password_change_done,
       {'template_name': 'auth/password_change_done.html'},
       name='auth_password_change_done'),
    url(r'^accounts/password/reset/$',
       auth_views.password_reset,
       {'template_name': 'auth/password_reset_form.html',
        'email_template_name': 'auth/password_reset_email.html'},
       name='auth_password_reset'),
    url(r'^accounts/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'auth/password_reset_confirm.html'},
       name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'auth/password_reset_complete.html'},
       name='auth_password_reset_complete'),
    url(r'^accounts/password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'auth/password_reset_done.html'},
       name='auth_password_reset_done'),
)

airtkts/apps/events/models.py
import datetime
import hashlib
import random
import re

from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.text import slugify
from .managers import EventManager, TicketSaleManager, InvitationManager

try:
    from django.utils.timezone import now as datetime_now
except ImportError:
    datetime_now = datetime.datetime.now

SHA1_RE = re.compile('^[a-f0-9]{40}$')


class Event(models.Model):
    slug = models.SlugField(blank=True)
    name = models.CharField(max_length=100)
    owner = models.ManyToManyField(User, related_name='owner')
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.CharField(max_length=100)

    objects = EventManager()

    class Meta:
        permissions = (
            ('view_event', 'Can view event'),
            ('search_hosts', 'Can search event hosts'),
            ('add_hosts', 'Can add event hosts'),
            ('change_hosts', 'Can edit event hosts'),
            ('delete_hosts', 'Can delete event hosts'),
            ('view_event_ticketsale', 'Can view event ticket sale'),
            ('add_event_ticketsale', 'Can add event ticket sale'),
            ('change_event_ticketsale', 'Can edit event ticket sale'),
            ('delete_event_ticketsale', 'Can delete event ticket sale'),
        )

    def save(self, *args, **kwargs):
        # Convert Name of Event to Slug
        if self.slug == '':
            self.slug = slugify(unicode(self.name))

        super(Event, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class TicketSale(models.Model):

    INVALID = 400
    SOLD_OUT = 500

    slug = models.SlugField(blank=True, null=True, default=None)
    icon_name = models.CharField(max_length=25, default='ticket', null=True)
    event = models.ForeignKey(Event)
    name = models.CharField(max_length=100)
    description = models.TextField(default='', blank=True)
    quantity = models.IntegerField()
    price = models.PositiveIntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    minimum_ordered = models.PositiveIntegerField(default=1)
    maximum_ordered = models.PositiveIntegerField()
    show_remaining_count = models.BooleanField(default=False)

    objects = TicketSaleManager()

    class Meta:
        permissions = (
            ('view_ticketsale', 'Can view ticket sale'),
        )

    def save(self, *args, **kwargs):
        # Convert Name of Event to Slug
        if self.slug == '':
            self.slug = slugify(unicode(self.name))

        super(TicketSale, self).save(*args, **kwargs)

    def has_tickets_remaining(self):
        return True

    def __unicode__(self):
        return "{event}: {name}".format(name=self.name, event=self.event.name)


class TicketOrder(models.Model):
    CREDIT_CARD = 'cc'
    CASH = 'cash'

    PAYMENT_METHODS = (
        (CASH, 'Cash'),
        (CREDIT_CARD, 'Credit Card')
    )

    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHODS, default=CREDIT_CARD)
    customer = models.CharField(max_length=50, blank=True, null=True)
    charge = models.CharField(max_length=100, blank=True, null=True)
    purchase_time = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    balance = models.DecimalField(decimal_places=2, max_digits=8, default=0)


class Ticket(models.Model):
    sale = models.ForeignKey(TicketSale)
    purchase = models.ForeignKey(TicketOrder)
    validated = models.BooleanField(default=False)
    name = models.CharField(max_length=75)


class Invitation(models.Model):
    USED_INVITE_KEY = 'ALREADY_BOUGHT_TICKETS'

    NO_ANSWER = '--'
    ATTENDING = 'ATTENDING'
    DECLINED = 'DECLINED'

    RSVP_CHOICES = (
        (NO_ANSWER, '--'),
        (ATTENDING, 'Attending'),
        (DECLINED, 'Decline'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    user = models.ForeignKey(User, blank=True, null=True)

    event = models.ForeignKey(Event)
    available_sales = models.ManyToManyField(TicketSale, blank=True, null=True)

    invited_by = models.ForeignKey('self', blank=True, null=True)
    max_guest_count = models.PositiveIntegerField(help_text='How many guests can this person invite? If '
                                                            'they are not allowed to invite guests then set this to 0.',
                                                  null=True, blank=True)
    guests = models.ManyToManyField('self', blank=True, null=True)

    invite_key = models.CharField(max_length=40, default='', blank=True, null=True)
    rsvp_status = models.CharField(choices=RSVP_CHOICES, default=NO_ANSWER, max_length=12)
    ticket_order = models.ForeignKey(TicketOrder, default=None, blank=True, null=True)

    invite_note = models.TextField(default=None, null=True, blank=True)
    sent_invite = models.TextField(default=False)

    objects = InvitationManager()

    class Meta:
        permissions = (
            ('view_invitation', 'Can view invitation'),
            ('change_own_invitation', 'Can change own invitation'),
        )

    def save(self, *args, **kwargs):

        if self.invite_key == '':

                salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
                username = self.email
                if isinstance(username, unicode):
                    username = username.encode('utf-8')
                invite_key = hashlib.sha1(salt+username).hexdigest()

                self.invite_key = invite_key

        return super(Invitation, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def can_bring_guests(self):
        """
        Determine whether this ``Invitation`` can bring a guest
        """

        # Super admins & Hosts can always add more
        if self.user is not None and self.user.has_perm('events.change_hosts', self.event):
            return True

        #
        return self.max_guest_count > 0 and self.max_guest_count > self.guests.all().count()

    def mark_used(self):
        """
        Mark this ``Invitation``'s invite key as expired
        """

        self.invite_key = self.USED_INVITE_KEY
        self.save()

    def invitation_key_expired(self):
        """
        Determine whether this ``Invitation``'s invite
        key has expired, returning a boolean -- ``True`` if the key
        has expired.

        Key expiration is determined by a two-step process:

        1. If the user has already bought a ticket, the key will have been
           reset to the string constant ``USED_INVITE_KEY``. Reusing an invite
           is not permitted, and so this method returns ``True`` in
           this case.

        2. Otherwise, it checks if the event has already passed and
           therefore the key has expired and this method returns ``True``.

        """
        return self.invite_key == self.USED_INVITE_KEY or (self.event.start_time <= datetime_now())

    invitation_key_expired.boolean = True

    def mail_guest(self, subject, body):
        msg = EmailMultiAlternatives(subject, '', None, [self.email, ])
        msg.attach_alternative(body, "text/html")
        msg.track_opens = True
        msg.track_clicks = True
        msg.auto_text = True
        msg.send()

    def invitation_email_message(self, request, note=None, subject_template='email/invite_email_subject.txt',
                                 email_template='email/invite_email.html', extra_context=None):

        current_site = get_current_site(request)
        site_name = current_site.name
        domain = current_site.domain

        if note is None and self.invite_note:
            note = self.invite_note

        context = {
            'email': self.email,
            'domain': domain,
            'event': self.event,
            'invited_by': self.invited_by,
            'site_name': site_name,
            'user': self,
            'note': note,
            'mailing_address': 'airTKTS <br/> 5980 Lerner Hall <br/>2920 Broadway <br/>New York, NY 10027',
            'protocol': 'https' if request.is_secure() else 'http',
        }

        if extra_context is not None:
            context.update(extra_context)
        subject = loader.render_to_string(subject_template, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())

        context.update({'subject': subject})

        email = loader.render_to_string(email_template, context)

        return subject, email

    def send_invitation_email(self, *args, **kwargs):
        """
        Send out an email to the holder of this ``Invitation`` reminding
        them to purchase a ticket to the event in question. Only sends
        out if the user's invite key is still valid
        """

        if not self.invitation_key_expired():
            subject, email = self.invitation_email_message(*args, **kwargs)
            self.mail_guest(subject, email)
            if not self.sent_invite:
                self.sent_invite = True
                self.save()

airtkts/apps/events/views.py
# Create your views here.

templates/events/base.html
{% extends 'base.html' %}

{% load permissions %}

{% block container %}

    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>{{ event.name }} <small>Edit your event</small></h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3">
            <ul class="nav nav-pills nav-stacked sidebar">
                <li><a href="{% url "event_dashboard" event.pk %}">
                    Dashboard
                </a></li>
                {% permission user has 'events.change_event' of event %}
                <li {% if section == 'event' %}class="active"{% endif %}><a href="{% url "event_edit" event.pk  %}">
                    Edit Event
                </a></li>
                {% endpermission %}
                {% permission user has 'events.add_hosts' of event %}
                <li {% if section == 'hosts' %}class="active"{% endif %}><a href="{% url "hosts_home" event.pk  %}">
                    Hosts
                </a></li>
                {% endpermission %}
                {% permission user has 'events.add_event_ticketsale' of event %}
                <li {% if section == 'ticketsales' %}class="active"{% endif %}><a href="{% url "ticketsales_home" event.pk  %}">
                    Tickets
                </a></li>
                {% endpermission %}
                <li {% if section == 'invites' %}class="active"{% endif %}><a href="{% url "invites_home" event.pk  %}">
                    Invitations
                </a></li>
            </ul>
        </div>
        <div class="col-lg-9">
            {% block content %}
            {% endblock %}
        </div>
    </div>

{% endblock %}

templates/events/check_in.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="apple-mobile-web-app-title" content="My App">
		<meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<title>Check in for {{ event.name }}</title>
		<link rel="stylesheet" href="{% static "css/checkin.css" %}" type="text/css" media="screen" />
	</head>
	<body class="ios7"> <!-- native | ios7 -->

        <div class="ui page dimmer"></div>

        <section id="view-home">
            <header class="titlebar">
                <button class="left arrow">
                    <div class="label" onclick="window.history.back();"> Back</div>
                </button>
                <h1>All Invites</h1>
            </header>
            <header class="search">
                <div class="search overlay">
                    <div class="content"><i class="search icon"></i> Search</div>
                </div>
                <i class="search icon input-group-addon"></i>
                <input type="search">
                <span class="search cancel">Cancel</span>
            </header>
            <div class="scrollMask"></div>
            <div class="scrollWrap">
                <div class="scroll">
                <div class="content tickets">
                    <div class="item">
                        <ul class="segmented control" id="ticket_filter">
                            <li class="control state active" data-filter="absent">Check In</li>
                            <li class="control state" data-filter="arrived">Arrived Guests</li>
                            <li class="control state" data-filter="all">All Guests</li>
                        </ul>
                    </div>
                    <ul class="arrowed">
                        {% for ticket in tickets %}
                        <li class="{% if ticket.validated %}arrived{% else %}absent{% endif %}">
                            <div class="swipeable ticket" data-pk="{{ ticket.pk }}">
                                <div class="big">{{ ticket.name }}</div>
                                <div class="light">{{ ticket.sale.name }}</div>
                                {% if ticket.purchase.balance < 0.00 %}<div class="balance">{{ ticket.purchase.balance }}</div>{% endif %}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            </div>
        </section>

        <script src="//code.jquery.com/jquery.js"></script>
        <script src="{% static 'js/vendor/django/jquery.cookie.js' %}"></script>
        <script src="{% static 'js/vendor/django/csrf.js' %}"></script>
        <script src="{% static 'js/vendor/hammer/hammer.min.js' %}"></script>
        <script src="{% static 'js/vendor/hammer/jquery.hammer.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery/jquery.clearsearch.js' %}"></script>
        <script src="{% static 'js/vendor/jquery/jquery.textchange.js' %}"></script>
        <script src="{% static 'js/vendor/jquery/jquery.hashchange.js' %}"></script>

        <script>
            _checkin_url = '{% url "check_in" event.pk %}';
            location.hash = 'absent';
        </script>
        <script src="{% static 'js/checkin.js' %}"></script>
	</body>
</html>

templates/events/event_dashboard.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %} {{ event.name }} Dashboard{% endblock %}

{% block extra_css %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/vendor/rickshaw/rickshaw.min.css' %}" rel="stylesheet" media="screen">
    <style>		.rickshaw_graph .detail .x_label { display: none }
		.rickshaw_graph .detail .item { line-height: 1.4; padding: 0.5em }
		.detail_swatch { float: right; display: inline-block; width: 10px; height: 10px; margin: 0 4px 0 0 }
		.rickshaw_graph .detail .date { color: #a0a0a0 }</style>
{% endblock %}
{% block container %}

    <h1>{{ event.name }} Dashboard</h1>

    <div class="row">
        <div class="col-lg-12">
            <a href="{% url "event_edit" event.pk  %}" class="btn btn-lg btn-default">Edit Event</a>
            <a href="{% url "ticketsales_home" event.pk  %}" class="btn btn-lg btn-default">View Tickets</a>
            <a href="{% url "invites_home" event.pk  %}" class="btn btn-lg btn-default">View Invitations</a>
            <a href="{% url "hosts_home" event.pk  %}" class="btn btn-lg btn-default">Edit Hosts</a>
            <a href="{% url "check_in" event.pk  %}" class="btn btn-lg btn-default">Check In Guests</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3">
            <div class="dashboard widget">
                <div class="content">
                    <div class="top left">Today</div>
                    <div class="top right">12&deg;</div>
                    <div class="huge numbers">{% now "H:i" %}<small>{% now "a" %}</small></div>
                    <div class="small text">{% now "l / M d / Y" %}</div>
                </div>
                <div class="footer">
                    <div class="title">New York, NY</div>
                    <a class="settings"></a>
                </div>
            </div>
            <div class="dashboard widget">
                <div class="content">
                    <div class="huge numbers"><span class="increase">{{ revenue }}</span></div>
                    <div class="small text ">dollars in revenue</div>
                </div>
                <div class="footer">
                    <div class="title">Revenue</div>
                    <a class="settings"></a>
                </div>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="dashboard widget double height">
                <div class="content">
                    <div class="huge numbers">{{ ticketcount }}</div>
                    <div class="small text">tickets purchased</div>
                    <div id="ticketsales_chart"></div>
                </div>
                <div class="footer">
                    <div class="title">New York, NY</div>
                    <a class="settings"></a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/vendor/rickshaw/d3.min.js' %}"></script>
    <script src="{% static 'js/vendor/rickshaw/d3.layout.min.js' %}"></script>
    <script src="{% static 'js/vendor/rickshaw/rickshaw.min.js' %}"></script>
    <script src=""></script>
    <script>
    $(document).ready(function (){
       var graph = new Rickshaw.Graph( {
            element: document.getElementById("ticketsales_chart"),
            renderer: 'line',
            height: 350,
            width: 800,
            series: [
                {
                    data: [ {% for tickets in ticketsales %} { x: {{ tickets.purchase_date|date:"U" }}, y: {{tickets.created_count}} },{% endfor %} ],
                    color: "#c05020",
                    name: "Tickets Sold"
                }
            ]
        } );

        var hoverDetail = new Rickshaw.Graph.HoverDetail( {
            graph: graph,
            formatter: function(series, x, y) {
                var date = '<span class="date">' + new Date(x * 1000).toUTCString() + '</span>';
                var swatch = '<span class="detail_swatch" style="background-color: ' + series.color + '"></span>';
                var content = swatch + series.name + ": " + parseInt(y) + '<br>' + date;
                return content;
            }
        } );

        graph.render();
    });

    </script>
{% endblock %}

templates/events/event_form.html
{% extends extends %}

{% load staticfiles %}
{% load widget_tweaks %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "css/vendor/admin/dual_listbox.css" %}">
    <link rel="stylesheet" href="{% static "css/vendor/datetimepicker/datetimepicker.css" %}">
{% endblock %}
{% block content %}

    <h1>{% if event.name %}Edit '{{ event.name }}' {% else %}Create an Event{% endif %}</h1>

    {% if form.non_field_errors %}
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">×</a>
            {{ form.non_field_errors }}
        </div>
    {% endif %}

    {{ form.errors }}

    <form method="post" class="form-horizontal"{% if has_file_field %} enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}

        <h2>Add your Event Details</h2>

        <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                <label class="col-lg-2 control-label" for="id_{{ form.name.html_name }}">Your Event {{ form.name.label }}</label>
                <div class="col-lg-10">
                    {% render_field form.name class+="form-control" %}
                    <p class="help-block">{{ form.name.help_text|safe }}{% if form.name.errors %}<strong>{{ form.name.errors }}</strong>{% endif %}</p>
                </div>
        </div>

        <div class="form-group {% if form.location.errors %}has-error{% endif %}">
                <label class="col-lg-2 control-label" for="id_{{ form.location.html_name }}">{{ form.location.label }}</label>
                <div class="col-lg-10">
                    {% render_field form.location class+="form-control" %}
                    <p class="help-block">{{ form.location.help_text|safe }}{% if form.location.errors %}<strong>{{ form.location.errors }}</strong>{% endif %}</p>
                </div>
        </div>

        <div class="form-group {% if form.location.errors %}has-error{% endif %}">
                <label class="col-lg-2 control-label" for="id_{{ form.location.html_name }}">Date & Time</label>
                <div class="col-lg-10">
                <div class="input-group">
                    {% render_field form.start_time class+="form-control" %}
                    <span class="input-group-addon">until</span>
                    {% render_field form.end_time class+="form-control" %}
                </div>

                    <p class="help-block">{{ form.start_time.help_text|safe }} {{ form.end_time.help_text|safe }}{% if form.start_time.errors %}<strong>{{ form.start_time.errors }}</strong>{% endif %} {% if form.end_time.errors %}<strong>{{ form.end_time.errors }}</strong>{% endif %}</p>
                </div>
        </div>

        <div class="form-group {% if form.description.errors %}has-error{% endif %}">
                <label class="col-lg-2 control-label" for="id_{{ form.description.html_name }}">{{ form.description.label }}</label>
                <div class="col-lg-10">
                    {% render_field form.description class+="form-control" %}
                    <p class="help-block">{{ form.description.help_text|safe }}{% if form.description.errors %}<strong>{{ form.description.errors }}</strong>{% endif %}</p>
                </div>
        </div>

        <div class="form-group {% if form.owner.errors %}has-error{% endif %}">
                <label class="col-lg-2 control-label" for="id_{{ form.owner.html_name }}">{{ form.owner.label }}</label>
                <div class="col-lg-10">
                    {% render_field form.owner class+="form-control" %}
                    <p class="help-block">{{ form.owner.help_text|safe }}{% if form.owner.errors %}<strong>{{ form.owner.errors }}</strong>{% endif %}</p>
                </div>
        </div>


        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}

        <div class="row">
            <div class="col-md-10 col-md-offset-2 hidden-xs">
                <input type="submit" class="btn btn-primary" value="Continue & Add Tickets" class="default" name="_continue">
                <input type="submit" class="btn" value="Save Event & Add Tickets Later" name="_save">
            </div>
        </div>

        <div class="form-actions hidden-md hidden-lg hidden-sm ">
            <input type="submit" class="btn btn-primary btn-block btn-lg" value="Continue & Add Tickets" class="default" name="_continue">
            <input type="submit" class="btn btn-block btn-lg" value="Save Event & Add Tickets Later" name="_save">
        </div>
    </form>

{% endblock %}
{% block extra_js %}
    <script src="{% static "js/vendor/admin/dual_listbox.js" %}"></script>
    <script src="{% static "js/vendor/datetimepicker/bootstrap-datetimepicker.js" %}"></script>
    <script>
    $('#id_owner').bootstrapDualListbox();
    $('#id_start_time, #id_end_time').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 0
    });
    </script>
{% endblock %}

templates/events/event_home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <h1>Select Events to Change</h1>
                <div class="bulk-actions">
                    <div class="pull-left">
                        <div>Action:
                            <select name="action">
                                <option value="" selected="selected">---------</option>
                                {% for action in actions %}
                                    <option value="{{ action.action }}">{{ action.description }}</option>
                                {% endfor %}
                            </select>
                            <input type="submit" class="btn btn-default" value="Go" name="_bulkactions">
                            <span class="action-counter" style="display: inline;"><span class="selected-count">0</span> of {{ events|length }} selected</span>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{% url "event_new" %}">Add User</a>
                    </div>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="action-toggle" style="display: inline-block;"></th>
                            <th>Name</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                            <th>Location</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for event in events %}
                            <tr>
                                <td class="action-checkbox"><input class="action-select" name="_selected_action" type="checkbox" value="{{ event.pk }}"></td>
                                <td><a href="{% url "event_dashboard" event.pk %}">{{ event.name }}</a></td>
                                <td>{{ event.start_time }}</td>
                                <td>{{ event.end_time }}</td>
                                <td>{{ event.location }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5" style="text-align: center">No one was found in this call tree.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </form>
{% endblock %}
{% block extra_js %}
    <script src="{% static "js/vendor/admin/bulk-actions.js" %}"></script>
    <script>var _max_bulk_item_count={{ events|length }}; var _current_bulk_item_count=0</script>
{% endblock %}